### ISSUE TITLE
search box?

### ISSUE THREAD

**Issue by tunnckoCore** [npm1k/npm1k.github.io#11]
for faster discovery

**Comment by kemitchell** [comment]
@tunnckoCore, what do you have in mind for the search box? Would it filter the list of wanted packages?

**Comment by tunnckoCore** [comment]
Mm yea, I missed to describe it. I think for input box in which you type some package name and the table is updated to contain only that package or packages with similar names. 

We can use [fuzzysearch](https://github.com/bevacqua/fuzzysearch) or [horsey](http://bevacqua.github.io/horsey/)

**Comment by tunnckoCore** [comment]
Another thing can be to type package name which isn't in Top1000 and check his license.

**Comment by kemitchell** [comment]
I'm not opposed to either of these, but I'm not in a position to implement myself.

To the extent others want to run with various front-end improvements, I would recommend that we use the generate script to create a JSON file that's fetched async on load, to make experimenting with browser-side scripts easier.

**Comment by tunnckoCore** [comment]
Mm yea, good idea, it would be better.

**Comment by kemitchell** [comment]
The list of "wanted" packages is getting small enough that I think this is less and less necessary. Closing for now. Please reopen if you'd like to discuss a PR!

**Comment by tunnckoCore** [comment]
Yea, no problem. It's was a long time ago.
