### ISSUE TITLE
show author

### ISSUE THREAD

**Issue by dylang** [npm1k/npm1k.github.io#12]
to make easier to search for packages you own, though I do like how clean it is right now.

**Comment by kemitchell** [comment]
@dylang, thanks for your comment!

I ran a quick scan on your user name using dat-npm. Here are a the packages with missing or old-style license metadata that I found:
- [logging](http://npmjs.com/packages/logging)
- [changelog](http://npmjs.com/packages/changelog)

Both use an old Ruby-style `licenses` array.

Really impressive body of work you've got. Thanks so much for contributing to open source!

**Comment by dougwilson** [comment]
I just had to eye ball the list, lol, but I can see how it's lame.

**Comment by dylang** [comment]
Cool, thanks, great work!
