### ISSUE TITLE
website down?

### ISSUE THREAD

**Issue by dotnetCarpenter** [npm1k/npm1k.github.io#15]
I just get an blank page.

Response headers:

```
HTTP/1.1 304 Not Modified

Date: Mon, 23 Nov 2015 01:32:43 GMT

Connection: keep-alive

Last-Modified: Thu, 01 Oct 2015 17:01:39 GMT

Access-Control-Allow-Origin: *

Expires: Mon, 23 Nov 2015 01:42:43 GMT

Cache-Control: max-age=600

Server: cloudflare-nginx

CF-RAY: 24991f31335536f6-ARN
```

**Comment by kemitchell** [comment]
`bin/generate` is failing, resulting in an empty `index.html`. I'm looking into it.

**Comment by kemitchell** [comment]
`bin/generate` seems to be broken. It's within github-package-json. I will revert to an old build and stop the cronjob that's been updating the page.

**Comment by kemitchell** [comment]
Back up, but out of date.
