### ISSUE TITLE
socket.io is now ready

### ISSUE THREAD

**Issue by Delapouite** [npm1k/npm1k.github.io#16]
Hello.

Since this PR last May : https://github.com/socketio/socket.io/commit/98af793f077e13cf06a3bc1afec7dbe281344308

socket.io now has a MIT license.

**Comment by kemitchell** [comment]
Hello! Thanks for the news.

Unfortunately, this site is quite out of date. The build script has been failing for some time.

I will try to strip out features so we can get something up-to-date online.

**Comment by kemitchell** [comment]
I got the site generator working again. socket.io no longer appears!

Thanks again for opening this issue!
