### ISSUE TITLE
is it useful to also check the repo and see if the package.json there has a valid SPDX identifier?

### ISSUE THREAD

**Issue by beaugunderson** [npm1k/npm1k.github.io#2]
meaning that the change has already been made and just needs to be published to npm?

**Comment by kemitchell** [comment]
@beaugunderson, it's a great point! A package may very well fix the problem and then have to wait awhile for the next release.

Then again, the point of licensing metadata is to communicate a clear license to others. That communication doesn't happen until the copy that users receive from npm has good metadata.

**Comment by beaugunderson** [comment]
would be helpful for those forking/creating pull requests though to know that that part is already done :)

**Comment by beaugunderson** [comment]
I also just made a PR for `q` and it might be nice to capture that somehow as well? (though not sure how to capture those easily, other than have the branch name in the PR have the word 'spdx' in it?)

**Comment by kemitchell** [comment]
I've created several pull requests myself. Thankfully, some were merged very quickly. Now they're green!

As for the site, I'm not sure I have the time to make npm1K a "real-time" dashboard, either with respect to the state of npm or the state of GitHub, though I do intend to improve the site. Pull requests for large or small improvements are most welcome!

**Comment by beaugunderson** [comment]
will see if I can get a PR for the first piece (fixed but not published) done :)

**Comment by kemitchell** [comment]
Sounds good!

**Comment by kemitchell** [comment]
@beaugunderson, I hope you don't mind if I go ahead and close this issue. Please feel free to reference it in a pull request!
