### ISSUE TITLE
HTTPS please

### ISSUE THREAD

**Issue by domenic** [npm1k/npm1k.github.io#3]
It is unfortunate that a resource like this is not accessible over HTTPS :(.

An easy way to set this up for gh-pages hosted sites is to use CloudFlare.

**Comment by kemitchell** [comment]
@domenic, thanks for your note!

**Comment by kemitchell** [comment]
@domenic, I'm trying CloudFlare as you suggested. The DNS server swap is propagating.

Was there any particular concern about unencrypted traffic to the site, or was it more a matter of principle?

**Comment by kemitchell** [comment]
https://npm1k.org is live.

**Comment by domenic** [comment]
Awesome, thank you! Honestly it was mostly a matter of principle...

It might be good to set up a 301 from the http version, turn on HSTS<del>, and update the repo link on GitHub</del><ins>I see you already did this since I checked last night :)</ins>. The former two can both be done from CloudFlare.

**Comment by kemitchell** [comment]
I'm down, but I'll get to it when I can.
