### ISSUE TITLE
return back the colorful rows

### ISSUE THREAD

**Issue by tunnckoCore** [npm1k/npm1k.github.io#8]
it was cool and faster to detect

**Comment by kemitchell** [comment]
Hello! Thanks for your feedback.

I removed the coloring when I removed listings for packages that already have correct metadata. Right now, every package listed has some kind of problem.

I suppose we could color red those packages that completely lack license metadata. Would definitely merge that PR.

**Comment by tunnckoCore** [comment]
> I suppose we could color red those packages that completely lack license metadata.

yea and orange that are invalid

it would be good someone to come to do the pr lol

**Comment by tunnckoCore** [comment]
@kemitchell cool, definitely better :)
